version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/node:14.14.0'
    steps:
      - run: cd client && npm i
      - run: cd client && npm run build
workflows:
  node-tests:
    jobs:
      - build

